repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: [
          "--profile", "black",  # Compatibility with black
          "--filter-files"
        ]
  # Analog of isort: https://github.com/asottile/reorder_python_imports

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]
        args: [
          "--max-doc-length=88",
          "--max-line-length=88",  # Compatibility with black
          "--extend-ignore=E203"  # Compatibility with black
        ]
  # List of all Flake8 rules: curl https://www.flake8rules.com/api/rules.json

  - repo:  https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.10
        exclude: "dir1/|dir2/|file1|file2"

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.4
    hooks:
      - id: vulture
        args: [".", "--exclude", "*venv*,*.toml,*yaml,*.yml", "--min-confidence", "70"]
  # Analog of vulture: https://github.com/asottile/dead